# Generated by Django 2.1.3 on 2019-01-02 07:44

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import healthrecords.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthstandards', '0001_initial'),
        ('serviceaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('gender', models.CharField(choices=[(healthrecords.models.FormGenderChoice('Male'), 'Male'), (healthrecords.models.FormGenderChoice('Female'), 'Female'), (healthrecords.models.FormGenderChoice('Both'), 'Both'), (healthrecords.models.FormGenderChoice('General'), 'General')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_examinations', to='serviceaccounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_field', to='healthrecords.Examination')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_records', to='healthrecords.Examination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_examination_records', to='serviceaccounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationRecordField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('examination_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_field_results', to='healthrecords.ExaminationField')),
                ('examination_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examination_record_results', to='healthrecords.ExaminationRecord')),
            ],
        ),
        migrations.CreateModel(
            name='StanardTestfieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_test_mapping', to='healthstandards.TestStandard')),
            ],
        ),
        migrations.CreateModel(
            name='StandardExamfieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_field', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='examinationfield_standard', to='healthrecords.ExaminationField')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_examination_mapping', to='healthstandards.ExaminationStandard')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('gender', models.CharField(choices=[(healthrecords.models.FormGenderChoice('Male'), 'Male'), (healthrecords.models.FormGenderChoice('Female'), 'Female'), (healthrecords.models.FormGenderChoice('Both'), 'Both'), (healthrecords.models.FormGenderChoice('General'), 'General')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_tests', to='serviceaccounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='TestField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='TestFieldTypeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('index', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestFieldValidBoolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('test_record_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_valid_boolean', to='healthrecords.TestField')),
            ],
        ),
        migrations.CreateModel(
            name='TestFieldValidFloatRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang_or_not', models.BooleanField()),
                ('value', django.contrib.postgres.fields.ranges.FloatRangeField()),
                ('test_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_valid_float_range', to='healthrecords.TestField')),
            ],
        ),
        migrations.CreateModel(
            name='TestFieldValidIntArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('test_record_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_valid_Integer_Array', to='healthrecords.TestField')),
            ],
        ),
        migrations.CreateModel(
            name='TestFieldValidStrArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('test_record_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_valid_String_Array', to='healthrecords.TestField')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_records', to='healthrecords.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_test_records', to='serviceaccounts.Member')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecordField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=511)),
                ('test_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_result', to='healthrecords.TestField')),
                ('test_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_record_results', to='healthrecords.TestRecord')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecordFieldBooleanValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('test_record_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_boolean_result', to='healthrecords.TestRecordField')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecordFieldFloatRangeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang_or_not', models.BooleanField()),
                ('value', django.contrib.postgres.fields.ranges.FloatRangeField()),
                ('test_record_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_float_result', to='healthrecords.TestRecordField')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecordFieldIntegerArrayValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang_or_not', models.BooleanField()),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('test_record_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_integer_array_result', to='healthrecords.TestRecordField')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecordFieldStringValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1023), size=None)),
                ('test_record_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_string_array_result', to='healthrecords.TestRecordField')),
            ],
        ),
        migrations.AddField(
            model_name='testfield',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_type', to='healthrecords.TestFieldTypeChoice'),
        ),
        migrations.AddField(
            model_name='testfield',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_field', to='healthrecords.Test'),
        ),
        migrations.AddField(
            model_name='stanardtestfieldmapping',
            name='test_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='test_field_standard', to='healthrecords.TestField'),
        ),
    ]
