# Generated by Django 2.1.3 on 2019-01-02 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('is_snomed', models.BooleanField(default=False)),
                ('is_icd_ten', models.BooleanField(default=False)),
                ('is_icd_nine', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IcdNine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IcdTen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loinc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snomed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('is_loinc', models.BooleanField(default=False)),
                ('is_local', models.BooleanField(default=False)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='local_standard', to='healthstandards.Local')),
                ('loinc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loinc_standard', to='healthstandards.Loinc')),
            ],
        ),
        migrations.AddField(
            model_name='examinationstandard',
            name='icd_nine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='icd_nine_standard', to='healthstandards.IcdNine'),
        ),
        migrations.AddField(
            model_name='examinationstandard',
            name='icd_ten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='icd_ten_standard', to='healthstandards.IcdTen'),
        ),
        migrations.AddField(
            model_name='examinationstandard',
            name='snomed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snomed_standard', to='healthstandards.Snomed'),
        ),
    ]
